---
title: "Day 2 Tasks"
author: "Matteo Torres"
format: html
editor_options: 
  chunk_output_type: console
---

## Checking data types

```{r}
# create a vector called vec_1
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)
```

```{r}
# data exploration
class(vec_1) # numeric
typeof(vec_1) # double
```

```{r}
# exercises
vec_1_e3 <- vec_1[3]
vec_1_e3

vec_1_e1 <- vec_1[1]
vec_1_e1

vec_1_e5to7 <- vec_1[5:7]
vec_1_e5to7

vec_1_char <- as.character(vec_1)
vec_1_char
```

```{r}
# create a vector called vec_2
vec_2 <- c(town = "Santa Barbara", location = "Rincon", swell = "south")
vec_2
```

```{r}
# data exploration
class(vec_2) # character
length(vec_2) # 3
```

```{r}
# exercises
vec_2_e2 <- vec_2[[2]]
vec_2_e2
```

```{r}
# create a data frame
df_1 <- data.frame(region = c("A", "B", "A", "D"), 
                   species = c("otter", "great white", "sea lion", "gray whale"), 
                   count = c(12, 2, 36, 6))
df_1
```

```{r}
# data exploration
class(df_1) # data frame
max_count <- max(df_1$count)
max_count # 36
```
